export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER = "SET_USER";
export const APP_READY = "APP_READY";
export const AUTHORIZED = "AUTHORIZED";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const RESET_DATA = "RESET_DATA";

export const ADD_FOLLOW = "ADD_FOLLOW";
export const UNFOLLOW = "UNFOLLOW";
export const CHART_DATA = "CHART_DATA";
export const ADD_VACATION = "ADD_VACATION";
export const OPEN_MODAL_ADD_VACATION = "OPEN_MODAL_ADD_VACATION";
export const DELETE_VACATION = "DELETE_VACATION";
export const UPDATE_VACATION = "UPDATE_VACATION";
export const EDIT_VACATION = "EDIT_VACATION";
export const OPEN_MODAL_EDIT_VACATION = "OPEN_MODAL_EDIT_VACATION";
export const CHECK_AUTH_VACATION = "CHECK_AUTH_VACATION";
export const FETCH_VACATIONS_SUCCESS = "FETCH_VACATIONS_SUCCESS";
export const FETCH_VACATIONS_FAILED = "FETCH_VACATIONS_FAILED";


export const SNACKBAR = {
  OPEN: "OPEN_SNACKBAR",
  CLOSE: "CLOSE_SNACKBAR",
};


export const MODAL_EDIT_MODE = "MODAL_EDIT_MODE";
export const MODAL_ADD_MODE = "MODAL_ADD_MODE";
export const MODAL_DELETE_MODE = "MODAL_DELETE_MODE";
export const MODAL_CHART_MODE = "MODAL_CHART_MODE";

